### ISSUE TITLE
Routing to /admin fails on first attempt

### ISSUE THREAD

**Issue by supdegrave** [hharnisc/meteor-accounts-admin-ui-bootstrap-3#12]
I'm currently working on an app, using roles + iron-router. I've added the appropriate router code as outlined at https://atmospherejs.com/package/accounts-admin-ui-bootstrap-3#iron-router-integration. 

I have created an account with admin role and am logged in with that account. When I manually navigate from any page in my app to /admin, the routing initially fails on the `Roles.userIsInRole` check, redirecting me to /. 

If I then navigate back in my browser history, the admin page renders successfully. 

Using: 
meteor: 0.8.0
accounts-admin-ui-bootstrap-3: 0.2.5
roles: 1.2.8
iron-router: 0.7.0

**Comment by supdegrave** [comment]
Note, this issue apparently only occurs if navigating by changing the URL manually. I've added a link to /admin now, and that works as expected. 

As such, priority on this is probably pretty low, but it may still be worth looking into.

**Comment by hharnisc** [comment]
Can you confirm a potential fix:

``` javascript
    this.route('admin', {
        path:'/admin',
            template: 'accountsAdmin',
            onBeforeAction: function() {
                if (Meteor.loggingIn()) {
                    this.render(this.loadingTemplate);
                } else if(!Roles.userIsInRole(Meteor.user(), ['admin'])) {
                    console.log('redirecting');
                    this.redirect('/');
                }
        }
    });
```

**Comment by supdegrave** [comment]
That seems to do the trick. Both navigating by link and by editing the address bar work exactly as expected. 

Thanks, Harrison!
