### ISSUE TITLE
Remove explicit bootstrap-3 dependency

### ISSUE THREAD

**Issue by johnm** [hharnisc/meteor-accounts-admin-ui-bootstrap-3#18]
Would you be willing to remove the explicit dependency on the bootstrap-3 package?

The problem is that we're using the less-bootstrap-3 package and having both packages in the project causes problems (bloat, confusing source maps, etc.).

This should be quite safe since anybody using your package is obviously already using bootstrap-3 one way or another. Removing the explicit dependency would allow for easier use by people using Less or incorporating the Bootstrap code directly.

Thanks,
John

**Comment by hharnisc** [comment]
I've tested and pulled in your changes. Thank you!
