### ISSUE TITLE
Error: Role already exists. [403]

### ISSUE THREAD

**Issue by jayfallon** [hharnisc/meteor-accounts-admin-ui-bootstrap-3#2]
When I add my user id to app.js, I keep getting an error:

`W20140203-15:36:32.985(-5)? (STDERR) /Users/jayfallon/.meteor/tools/09b63f1ed5/lib/node_modules/fibers/future.js:206
W20140203-15:36:32.985(-5)? (STDERR)                        throw(ex);
W20140203-15:36:32.986(-5)? (STDERR)                              ^
W20140203-15:36:32.992(-5)? (STDERR) Error: Role already exists. [403]`

Meteor version: 0.7.0.1

Thanks for any help!

**Comment by hharnisc** [comment]
The startup code is trying to create a role that already exists, which the Roles libs are throwing an exception.  I missed this in the documentation.  

In **app.js** change

``` javascript
Roles.createRole("secret");
Roles.createRole("double-secret");
```

to

``` javascript
if(!Meteor.roles.findOne({name: "secret"}))
    Roles.createRole("secret");
if(!Meteor.roles.findOne({name: "double-secret"}))
    Roles.createRole("double-secret");
```

This only adds a new role if one does not exist. 

Thanks for catching this! I'm updating the docs.
