### ISSUE TITLE
Redirect after login not work

### ISSUE THREAD

**Issue by dofrance** [hharnisc/meteor-accounts-admin-ui-bootstrap-3#20]
I try to run the demo app, login with the admin user/role is fine but the redirect function not work 

```
console.log('redirecting');
this.redirect('/admin');
```

it also not print anything to the console

**Comment by hharnisc** [comment]
Could you paste the output of `meteor --version` ?
It's a safe bet that if you don't see any output in the console then the code is not getting called.

**Comment by dofrance** [comment]
Hi hharnisc,
My meteor is Release 0.8.2.

**Comment by hharnisc** [comment]
Just did a clean install (OS X) without any issues.  I'm going to close this, but lets keep working on this thread till we figure this out. The default admin is `admin@test.com` and password `admin` try that and let me know what happens.

**Comment by dofrance** [comment]
Yes, it work now!
Thank you so much ^^
