### ISSUE TITLE
Including bootstrap-modal separately breaks modals 

### ISSUE THREAD

**Issue by neoncrumpet** [hharnisc/meteor-accounts-admin-ui-bootstrap-3#3]
Had an issue where I was generating a modal on the page and it came up as below 

<a href="http://imgur.com/gvONyoo"><img src="http://i.imgur.com/gvONyoo.png" title="Hosted by imgur.com" /></a>

Discovered that it was the fact that the bootstrap modal css gets included twice - once in the `bootstrap-3/bootstrap.css` and once with the bootstrap-modal that is required in the package.json.

Fixed in the meantime by removing 
`api.use('bootstrap-modal', 'client');`
from the package.json. Don't know if this is something to look into or not.

**Comment by hharnisc** [comment]
You're absolutely right. Bootstrap 3 already includes the contents of modal packages.  Remove them from the package.  Thanks Shaun!
