### ISSUE TITLE
Sort of working, what am I missing?

### ISSUE THREAD

**Issue by clarkritchie** [hharnisc/meteor-accounts-admin-ui-bootstrap-3#6]
It seems like I have this working, though I only see my admin account in the main listing and I cannot edit it.  Search returns nothing.  Is this because my user "clark" has no role?  How would I make a default role for new users?

Mange roles adds/removes from my roles collection OK:

![screen shot 2014-03-12 at 10 42 11 am](https://f.cloud.github.com/assets/385550/2400718/bced2da4-aa0d-11e3-87fe-c2e8ef6b2494.png)

```
meteor:PRIMARY> db.roles.find().pretty();
{ "name" : "admin", "_id" : "hyCiF7pWoYoLhbZ2b" }
{ "name" : "secret", "_id" : "ouYr9qmydkvpWi42C" }
{ "name" : "foo", "_id" : "mxEQCgAG3yYZs6fBX" }
```

Only see my admin account in main listing when I'd like to assign user to a role:

![screen shot 2014-03-12 at 10 41 59 am](https://f.cloud.github.com/assets/385550/2400757/2fad5d46-aa0e-11e3-889e-51c96cd50eb1.png)

```
meteor:PRIMARY> db.users.find({},{"username":1,"roles":1}).pretty();
{
    "_id" : "Rzv28MrXpjvzaRTy7",
    "roles" : [
        "admin"
    ],
    "username" : "admin"
}
{ "_id" : "guaiG7fjp5SNadxco", "username" : "clark" }
```

**Comment by hharnisc** [comment]
**A couple of questions for you**

Are you viewing this template from a user who is currently logged in, and has the role 'admin' ?

To get an idea of what users are published take a look at this file:
https://github.com/hharnisc/meteor-accounts-admin-ui-bootstrap-3/blob/master/libs/user_query.js

Also if you go to the javascript console and type

> Meteor.users.find({}).fetch()

Do you see more than one user?

**Comment by clarkritchie** [comment]
Ah, yes -- users must have a role -- duh.

What might be the right approach for assigning a user to default role?

Is there an alternate admin UI for creating new users?  Right now I am only creating new users via the new user signup in accounts-ui-bootstrap-3, and bootstraping them in fixtures.js.

**Comment by clarkritchie** [comment]
So sorry, I think our comments overlapped...

I see now that it works when I bootstrap a user account and explicitly set a role for that user.

A few scenarios I am confused by:
- New users created via accounts-ui-bootstrap-3 default to having no role -- any recommendation on how to set a default role for new accounts?
- Perhaps this module might allow me to set a role for users who have no role (as above, my test user with no role was not returned in the listing and therefore uneditable)
- Admins can create new users and specify a role (maybe this is not yet implemented yet?)

Thanks so much, looking forward to working with this.

**Comment by hharnisc** [comment]
Users you're searching for don't need roles, but they do need one of the two subdocuments in the user object stored in mongo. 

> profile.name

or 

> emails.address

It looks like your user object only has

> username

Did you create this user by hand with the mongo shell or minimongo?

If you use one of meteor's built in account packages and and the account ui for bootstrap, the required fields are populated.

```
$ mrt add accounts-password
$ mrt add accounts-ui-bootstrap-3
```

You need {{ loginButtons }} embedded in one of your templates in order to see the login/signup UI.

But if you follow the [Quick Start](https://github.com/hharnisc/meteor-accounts-admin-ui-bootstrap-3#quick-start) it walks you through setting up a simple project with the Admin UI.

**Comment by clarkritchie** [comment]
Got it, thanks.  I had a rogue:

```
Accounts.ui.config({
  passwordSignupFields: 'USERNAME_ONLY'
});
```

Works much better with `USERNAME_AND_EMAIL`.  Cheers.

**Comment by hharnisc** [comment]
Getting my comments back in sync with yours :)

1) You could use the built in callback from meteor when a new user is created (untested)

``` javascript
Accounts.onCreateUser(function(options, user) {
  if (options.profile)
    user.profile = options.profile;
  Roles.addUsersToRoles(user, ['defaultRole']);
  return user;
});
```

2) Creating new users with the admin ui has not been implemented
