### ISSUE TITLE
Meteor 0.8.0-rc0 - error

### ISSUE THREAD

**Issue by pwujek** [hharnisc/meteor-accounts-admin-ui-bootstrap-3#7]
Got this error while testing Meteor 0.8.0-rc0, I'd fix it if I understood what it is about.

`While building package`accounts-admin-ui-bootstrap-3`:
client/accounts_admin.html:21: Reactive HTML attributes must either have a constant name or consist of a single {{helper}} providing a dictionary of names and values.  A template tag of type BLOCKOPEN is not allowed here.
...{#each users}}       <tr {{#if myself _id}} c...
                        ^`

**Comment by hharnisc** [comment]
Seems like it could be a bug (or a new feature) with bleeding edge Meteor build.

The line with the error

``` html
<tr {{#if myself _id}} class="info" {{/if}}>
```

The template helper **myself** is being passed a variable _id (which is the user id of each user looped in the template)

``` javascript
myself: function(userId) {
    return Meteor.userId() === userId;
}
```

The intent is to distinguish the current user from any other user.

I've posted a link back to this bug to with the Meteor team to get some feedback from an issue that appears to be related.

https://github.com/meteor/meteor/issues/1930

**Comment by dgreensp** [comment]
You have to move the #if after the class=.

**Comment by hharnisc** [comment]
I'm about to push a fix (thanks @dgreensp)

changed

``` html
<tr {{#if myself _id}} class="info" {{/if}}>
```

to

``` html
<tr class="{{#if myself _id}}info{{/if}}">
```

**Comment by baiqif** [comment]
How to deal with "checked"

**Comment by rafaelfaria** [comment]
+1 for the checked.

**Comment by unwitting** [comment]
@baiqif @rafaelfaria see https://github.com/meteor/meteor/wiki/Using-Blaze#conditional-attributes-with-no-value-eg-checked-selected:

`checked={{isChecked}}`
